version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.web
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./src:/usr/src/app
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

    mongodb:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.mongodb
        ports:
            - 27018:27017
        env_file:
            - .env
        command:
            [
                "mongod",
                "--keyFile",
                "/usr/src/mongo.key",
                "--replSet",
                "rs0",
                "--bind_ip",
                "0.0.0.0",
            ]
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
